suppliers:
  - name: Castorama
    base_url: "https://www.castorama.fr"
    categories:
      tiles:
        # Updated selectors for Castorama as per latest HTML structure
        product_selector: 'div[data-test-id="product-panel"]'
        name_selector: 'h3[data-test-id="productTitle"]'
        price_selector: 'div[data-test-id="product-primary-price"]'
        url_selector: 'a[data-test-id="product-panel-main-section"]'
        image_selector: 'img[data-test-id="image"]'
        brand_selector: ''  # Not present in snippet
        unit_selector: ''   # Not present in snippet
    pagination:
      next_button_selector: 'a[aria-label="Page suivante"]'
      infinite_scroll: false
  - name: ManoMano
    base_url: "https://www.manomano.fr"
    categories:
      tiles:
        product_selector: '[data-testid="productCardListing"]'
        name_selector: '[data-testid="product-card-listings-title"]'
        price_selector: '[data-testid="price-main"]'
        url_selector: '[data-testid="productCardListing"]'
        image_selector: '[data-testid="image"]'
        products_container: '[data-testid="products-layout-category"]'
        brand_selector: '[data-testid="brand-image"]'
    pagination:
      next_button_selector: 'button[aria-label="Next"]'
      infinite_scroll: false 